# Generated by Django 3.2.16 on 2024-03-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть комментарий.', verbose_name='Опубликовано'),
        ),
    ]
