# Generated by Django 3.2.16 on 2024-03-13 14:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_choice_result_testanswer_testquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['lesson__id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='qtype',
            new_name='question_type',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='explanation',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Текст теории', verbose_name='Текст теории'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='lessons.testquestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_questions', to='lessons.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Вопрос'),
        ),
    ]
