# Generated by Django 3.2.16 on 2024-03-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_rename_level_levelquestion_level_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'verbose_name': 'Уровень сложности', 'verbose_name_plural': 'Уровни сложности'},
        ),
        migrations.RemoveField(
            model_name='levelquestion',
            name='question',
        ),
    ]
