# Generated by Django 3.2.16 on 2024-03-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20240315_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelquestion',
            options={'verbose_name': 'Уровень сложности', 'verbose_name_plural': 'Уровни сложности'},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['lesson__id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='testquestion',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='level_questions', to='lessons.levelquestion', verbose_name='Уровень сложности'),
        ),
    ]
