# Generated by Django 3.2.16 on 2024-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Заработанные баллы'),
        ),
    ]
