# Generated by Django 3.2.16 on 2024-03-12 15:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Ответ'),
            preserve_default=False,
        ),
    ]
